// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqugwlwhkyxyclvxnsxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxdWd3bHdoa3l4eWNsdnhuc3htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MzU1ODUsImV4cCI6MjA2MzAxMTU4NX0.aEdDTkwAkBb1I_7BzMyamHhJBQjJ_A-cAMvr43sepnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);